[package]
name = "rasen-bridge"
version = "0.1.0"
authors = ["Léo-Paul COUTURIER <root@leops.me>"]

[lib]
name = "rasen"
crate-type = ["dylib"]

[dependencies]
serde = "0.8"
serde_json = "0.8"
spirv-utils = { git = "https://github.com/leops/spirv-utils.git", rev = "e421592" }
error-chain = "*"

[dependencies.rasen]
version = "0.5.0"
git = "https://github.com/leops/rasen.git"
rev = "68020c6"
